### ISSUE TITLE
Add `getTileData` function to fns

### ISSUE THREAD

**Issue by Bloomca** [Bloomca/redux-tiles#16]
Currently it is not very easy to get current data inside fn.
It is especially painful for sync tiles. E.g. from [todoMVC](https://github.com/Bloomca/redux-tiles/blob/master/examples/todomvc/src/tiles/todos.js#L38):

```js
    remove: ({ params, selectors, getState }) => {
      const list = selectors.todos.list(getState());
      return list.filter(item => item.id !== params.id);
    },
```

This part can also be pretty repetitive, so it might make sense to add it.

The problem is that the API surface will be increased, and the naming should be intuitive. `getTileData` seems pretty clumsy, but I have no idea except `getCurrentData`.

**Comment by HerrBastiii** [comment]
How about just `getData`?

**Comment by Bloomca** [comment]
Well I thought initially that it is too abstract, but actually it seems as a good idea:

```js
    remove: ({ getData, params }) => getData().filter(item => item.id !== params.id),
```

**Comment by HerrBastiii** [comment]
What would it return? The whole state or just that part scoped by its current tile?

**Comment by Bloomca** [comment]
I think it should return state of the current tile with nesting, if applied.

So, it will be a full equivalent of:

```js
fn({ selectors, getState, params }) => {
  const data = selectors.modules.calculator.offer(getState(), params);
 
  // the same thing will be:
  const data = getData();
}
```

I just find it pretty clumsy to write this line (`selectors.modules.calculator.offer(getState(), params);`) – a lot of stuff has to be destructured. It is mostly for sync tiles, where changes might depend on previous values (e.g. toggling).

**Comment by HerrBastiii** [comment]
Yes, I think the scoped part is the better choice. Also if it have to rely on part beyond the current data scope, the getState method is still there. 

You've got a "remove:" key word In your previous examples here. Is it something new ? Didn't saw it till now. :)

**Comment by Bloomca** [comment]
I've introduced `fns` (example in [todoMVC](https://github.com/Bloomca/redux-tiles/blob/master/examples/todomvc/src/tiles/todos.js#L26-L52)) for sync tiles – when I was writing this example, I realized that I perform different operations on the same data, so this separation seems pretty semantical for me. They behave exactly as normal functions, but accessible by one level deeper – e.g. `actions.tiles.todos.remove` or `actions.tiles.todos.add` – more semantic, but they still operate on the same data (so reducer is common).

You can take a look here – #11

**Comment by Bloomca** [comment]
Done in [0.9.0 release](https://github.com/Bloomca/redux-tiles/releases/tag/0.9.0).
